_id: O8SI0wuyso8KwqqA
_key: '!items!O8SI0wuyso8KwqqA'
_stats:
  coreVersion: '13.350'
img: systems/pf1/icons/feats/skill-focus.jpg
name: reconfigure
system:
  abilityType: ex
  associations:
    classes:
      - Aegis
  description:
    value: >-
      <p><b>reconfigure:</b>&nbsp;Starting&nbsp;at&nbsp;3rd&nbsp;level,&nbsp;an&nbsp;aegis&nbsp;can&nbsp;reconfigure&nbsp;up&nbsp;to&nbsp;his&nbsp;Intelligence&nbsp;modifier&nbsp;in&nbsp;customization&nbsp;points&nbsp;on&nbsp;his&nbsp;astral&nbsp;suit&nbsp;once&nbsp;per&nbsp;day&nbsp;as&nbsp;a&nbsp;standard&nbsp;action.&nbsp;Every&nbsp;two&nbsp;levels&nbsp;thereafter,&nbsp;he&nbsp;can&nbsp;use&nbsp;this&nbsp;ability&nbsp;an&nbsp;additional&nbsp;time&nbsp;per&nbsp;day.

      </p>
  subType: classFeat
  tag: reconfigure
type: feat
