_id: a8su0SOW4eIaGoWa
_key: '!items!a8su0SOW4eIaGoWa'
_stats:
  coreVersion: '13.350'
img: systems/pf1/icons/feats/skill-focus.jpg
name: Reconfigure
system:
  abilityType: ex
  associations:
    classes:
      - Aegis
  description:
    value: |-
      <p><b>Reconfigure:</b> Starting at 3rd level, an aegis can reconfigure up to his Intelligence modifier in customization points on his astral suit once per day as a standard action. Every two levels thereafter, he can use this ability an additional time per day.
      </p>
  subType: classFeat
  tag: reconfigure
type: feat
