_id: RG8YtlEHpgqRLDGV
_key: '!items!RG8YtlEHpgqRLDGV'
_stats:
  coreVersion: '13.350'
flags:
  pf1-psionics:
    sourceUrl: https://metzo.miraheze.org/wiki/Extra_Reconfiguration
img: icons/magic/symbols/runes-star-magenta.webp
name: Extra Reconfiguration
system:
  abilityType: none
  acquired: false
  changeFlags:
    heavyArmorFullSpeed: false
    immuneToMorale: false
    loseDexToAC: false
    lowLightVision: false
    mediumArmorFullSpeed: false
    noHeavyEncumbrance: false
    noMediumEncumbrance: false
    seeInDarkness: false
    seeInvisibility: false
  description:
    value: >-
      <p>You are able to modify your astral suit more often.

      </p>

      <p><strong>Prerequisites: </strong>Astral suit class ability, reconfigure

      class ability

      </p>

      <p><strong>Benefit: </strong>You gain one additional daily use of your

      reconfigure class ability.

      </p>

      <p><br /></p>

      <p>Your mythic energies grant you additional opportunities to reconfigure
      your astral suit.

      </p>

      <p><strong>Prerequisite:</strong> Extra Reconfiguration.

      <strong>Benefit:</strong> You gain one additional daily use of your
      reconfigure ability. Additionally, if you have no uses of reconfigure
      remaining, you may expend two uses of mythic power to use your reconfigure
      ability  Additionally, if you have no uses of reconfigure remaining, you
      may expend two uses of mythic power to use your reconfigure ability <br
      /></p>
  disabled: false
  featType: feat
  inherited: false
  showInQuickbar: false
  simple: false
  sources:
    - date: ''
      errata: ''
      id: ''
      pages: ''
      publisher: Dreamscarred Press
      title: Ultimate Psionics
    - date: ''
      errata: ''
      id: ''
      pages: ''
      publisher: Dreamscarred Press
      title: 'Psionics Augmented: Mythic Psionics'
    - date: ''
      errata: ''
      id: ''
      pages: ''
      publisher: Dreamscarred Press
      title: 'Psionics Expanded: Advanced Psionics Guide'
  subType: feat
  summons: false
  tags:
    - psionic
type: feat
