_id: 3j1kaaKTEVw5w4S1
_key: '!items!3j1kaaKTEVw5w4S1'
_stats:
  coreVersion: '13.350'
folder: cfT4dXvdFgQ6wbWS
img: icons/magic/symbols/runes-star-magenta.webp
name: Reconfigure
system:
  abilityType: ex
  associations:
    classes:
      - Aegis
  description:
    value: >-
      <p>Starting at 3rd level, an aegis can reconfigure up to his Intelligence
      modifier in customization points on his astral suit once per day as a
      standard action. Every two levels thereafter, he can use this ability an
      additional time per day.

      </p>
  sources:
    - date: '2012-07-23'
      pages: 27–31
      publisher: Dreamscarred Press
      title: Psionics Expanded
    - date: '2013-12-24'
      pages: 28–30
      publisher: Dreamscarred Press
      title: Ultimate Psionics
  subType: classFeat
  tag: reconfigure
type: feat
